language: node_js
node_js:
  - stable
  - iojs
  - '0.12'
os:
  - linux
  - osx
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then git clone https://github.com/creationix/nvm.git /tmp/.nvm; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source /tmp/.nvm/nvm.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then nvm install $TRAVIS_NODE_VERSION; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then nvm use --delete-prefix $TRAVIS_NODE_VERSION; fi
before_script:
  - npm install -g istanbul
  - npm install -g mocha
  - npm install -g coveralls
after_script:
  - npm run coverage
  - npm run coveralls
services:
  - redis-server